apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::233750735818:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1KKLX0YK1JAM1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::233750735818:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-05T14:09:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1433"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6bfaee9d-07df-47ea-a3ef-4ad45a1d9281
