apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::233750735818:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-V7NE6LG2LWME
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::233750735818:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-05T11:51:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1257"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fb6e94f4-3e0e-4520-833c-836c62c1d619
